### PR TITLE
bump kube-rbac-proxy

### PR DESCRIPTION
**Pull request by s-urbaniak**
/cc @stlaz

### CODE REVIEW

**Comment by slaskawi** [comment]
The code itself looks good to me. 

But I'd appreciate a few minor updates:
- Please squash your changes into two commits - one for updating the `OWNERS` and the other for updating the code.
- Please add some reference to Bugzilla or JIRA so that we know what is the context of this change.

**Comment by s-urbaniak** [comment]
@slaskawi this is a mechanical upstream bump, we don't squash upstream commits, the OWNERS change is a separate commit.

**Pull request merged**
