### PR TITLE
Remove hardcoded amd64 in build path

### PR DESCRIPTION
**Pull request by jeffdyoung**
Replace hardcoded 'amd64' so we can build other archs.

### CODE REVIEW

**Comment by metalmatze** [comment]
I think we could also do this fix upstream in @brancz project?

**Comment by brancz** [comment]
yes let's fix this upstream and then update this downstream fork

**Comment by jeffdyoung** [comment]
@brancz Do you want me to close this, and open a new PR upstream?

**Comment by brancz** [comment]
Yes, please :)

**Comment by jeffdyoung** [comment]
Closing so I can fork upstream.

**Comment by jeffdyoung** [comment]
@brancz Do I need to do anything to get this (https://github.com/brancz/kube-rbac-proxy/pull/21)
pulled in?

**Comment by brancz** [comment]
we need to merge/rebase this repo with the upstream state now, feel free to create a new PR for this

**Pull request closed without merging**
